version: "3.8"
services:
  web:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - db2
    environment:
      - DB_NAME=jmandpf_sns_db
      - DB_USER=root
      - DB_PASSWORD=team5
      - DB_HOST=db2
      - DB_PORT=3306
    command: python manage.py runserver 0.0.0.0:8001

  db2:
    image: mariadb:10.5
    container_name: mariadb_container
    environment:
      - MYSQL_DATABASE=jmandpf_sns_db
      - MYSQL_ROOT_PASSWORD=team5
      - MYSQL_ROOT_HOST=%
    volumes:
      - db_data:/var/lib/mysql
      - ./user_tbl.sql:/docker-entrypoint-initdb.d/user_tbl.sql
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/user_tbl.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db2
      PMA_USER: root
      PMA_PASSWORD: team5
    ports:
      - "8080:80"
    depends_on:
      - db2

volumes:
  db_data:
